# Generated by Django 5.1.4 on 2025-01-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_column', models.DateField(verbose_name='时间')),
                ('flow_direction', models.IntegerField(choices=[(0, '流向0'), (1, '流向1')], verbose_name='流向')),
                ('professional_company', models.CharField(max_length=255, verbose_name='专业公司')),
                ('business_type', models.CharField(max_length=100, verbose_name='业务类型')),
                ('byte_count', models.BigIntegerField(verbose_name='字节数')),
            ],
            options={
                'verbose_name_plural': '专业公司',
                'db_table': 'companyflow',
            },
        ),
    ]
